### ISSUE TITLE
Catalog 'flex' does not exist

### ISSUE THREAD

**Issue by tooptoop4** [ebyhr/presto-flex#13]
I followed cp -p target/*.jar ${PLUGIN_DIRECTORY}/flex/ and on startup looks ok (using prestosql 333)

2020-05-28T20:14:46.582Z        INFO    main    io.prestosql.server.PluginManager       -- Loading plugin /home/ec2-user/datap/plugin/flex --
2020-05-28T20:14:46.609Z        INFO    main    io.prestosql.server.PluginManager       Installing org.ebyhr.presto.flex.FlexPlugin
2020-05-28T20:14:46.622Z        INFO    main    io.prestosql.server.PluginManager       Registering connector flex
2020-05-28T20:14:46.623Z        INFO    main    io.prestosql.server.PluginManager       -- Finished loading plugin /home/ec2-user/datap/plugin/flex --

but query fails, is there any properties/catalog i need to specify?
```
select
  * 
from 
 flex.csv."https://raw.githubusercontent.com/ebyhr/presto-flex/master/src/test/resources/example-data/numbers-2.csv"
```

```
io.prestosql.spi.PrestoException: line 4:2: Catalog 'flex' does not exist
	at io.prestosql.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:57)
	at io.prestosql.sql.analyzer.SemanticExceptions.semanticException(SemanticExceptions.java:52)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:1028)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitTable(StatementAnalyzer.java:300)
	at io.prestosql.sql.tree.Table.accept(Table.java:53)
	at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:315)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.analyzeFrom(StatementAnalyzer.java:2307)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:1257)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuerySpecification(StatementAnalyzer.java:300)
	at io.prestosql.sql.tree.QuerySpecification.accept(QuerySpecification.java:144)
	at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:315)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:325)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:910)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.visitQuery(StatementAnalyzer.java:300)
	at io.prestosql.sql.tree.Query.accept(Query.java:107)
	at io.prestosql.sql.tree.AstVisitor.process(AstVisitor.java:27)
	at io.prestosql.sql.analyzer.StatementAnalyzer$Visitor.process(StatementAnalyzer.java:315)
	at io.prestosql.sql.analyzer.StatementAnalyzer.analyze(StatementAnalyzer.java:292)
	at io.prestosql.sql.analyzer.Analyzer.analyze(Analyzer.java:83)
	at io.prestosql.sql.analyzer.Analyzer.analyze(Analyzer.java:75)
	at io.prestosql.execution.SqlQueryExecution.analyze(SqlQueryExecution.java:217)
	at io.prestosql.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:176)
	at io.prestosql.execution.SqlQueryExecution.<init>(SqlQueryExecution.java:93)
	at io.prestosql.execution.SqlQueryExecution$SqlQueryExecutionFactory.createQueryExecution(SqlQueryExecution.java:705)
	at io.prestosql.dispatcher.LocalDispatchQueryFactory.lambda$createDispatchQuery$0(LocalDispatchQueryFactory.java:121)
	at io.prestosql.$gen.Presto_014fffb_dirty__333____20200528_201443_2.call(Unknown Source)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by tooptoop4** [comment]
@amiorin @combineads @rubik-ai @takezoe @chinaworld @junphine @youngwookim @szyn @minyk did u face this?

**Comment by ebyhr** [comment]
@tooptoop4  Please create `flex.properties` in the catalog directory.

**Comment by tooptoop4** [comment]
is there an example?
