### ISSUE TITLE
casing of URLs getting changed

### ISSUE THREAD

**Issue by tooptoop4** [ebyhr/presto-flex#18]
query submitted with

https://storage.googleapis.com/redact1/redact2.csv?x-goog-signature=bla&x-goog-algorithm=GOOG4-RSA-SHA256&x-goog-credential=redact%40redact.iam.gserviceaccount.com%2F20200526%2Fus-central1%2Fstorage%2Fgoog4_request ...some more redact stuff

but logs show:

https://storage.googleapis.com/redact1/redact2.csv?x-goog-signature=bla&x-goog-algorithm=goog4-rsa-sha256&x-goog-credential=redact%40redact.iam.gserviceaccount.com%2f20200526%2fus-central1%2fstorage%2fgoog4_request  ...some more redact stuff

GOOG4-RSA-SHA256 and  %2F got changed

```
2020-05-29T12:39:40.587Z        ERROR   remote-task-callback-16 io.prestosql.execution.StageStateMachine        Stage 20200529_123939_00075_39ep2.1 failed
java.io.UncheckedIOException: java.io.IOException: Server returned HTTP response code: 400 for URL: redact
        at org.ebyhr.presto.flex.FlexRecordCursor.<init>(FlexRecordCursor.java:83)
        at org.ebyhr.presto.flex.FlexRecordSet.cursor(FlexRecordSet.java:55)
        at io.prestosql.spi.connector.RecordPageSource.<init>(RecordPageSource.java:39)
        at io.prestosql.split.RecordPageSourceProvider.createPageSource(RecordPageSourceProvider.java:50)
        at io.prestosql.split.PageSourceManager.createPageSource(PageSourceManager.java:64)
        at io.prestosql.operator.TableScanOperator.getOutput(TableScanOperator.java:299)
        at io.prestosql.operator.Driver.processInternal(Driver.java:379)
        at io.prestosql.operator.Driver.lambda$processFor$8(Driver.java:283)
        at io.prestosql.operator.Driver.tryWithLock(Driver.java:675)
        at io.prestosql.operator.Driver.processFor(Driver.java:276)
        at io.prestosql.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1075)
        at io.prestosql.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
        at io.prestosql.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
        at io.prestosql.$gen.Presto_014fffb_dirty__333____20200529_123041_2.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Server returned HTTP response code: 400 for URL: redact
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
        at java.base/java.net.URL.openStream(Unknown Source)
        at com.google.common.io.Resources$UrlByteSource.openStream(Resources.java:70)
        at org.ebyhr.presto.flex.FlexRecordCursor.<init>(FlexRecordCursor.java:75)
        ... 16 more
```

**Comment by tooptoop4** [comment]
guess this is caused by https://github.com/prestosql/presto/issues/17

**Comment by tooptoop4** [comment]
@ebyhr is there any small patch that can be made on presto code for this?

**Comment by davidrabinowitz** [comment]
Yes, SchemaTableName converts both inputs to lower case - my guess to to keep the equals and hashcode consistent, but it does pose an issue when the data storage supports mixed case naming, such as BigQuery. My solution was to keep a mapping between the SchemaTableName and the name I got from the BigQuery API, so that I can use the BigQuery names when needed.

**Comment by tooptoop4** [comment]
I tried changing SchemaTableName like below but still same issue. Any ideas?

    @JsonCreator
    public SchemaTableName(@JsonProperty("schema") String schemaName, @JsonProperty("table") String tableName)
    {
        if (tableName.contains("://")) {
            this.schemaName = checkNotEmpty(schemaName, "schemaName");
            this.tableName = checkNotEmpty(tableName, "tableName");
        }
        else {
            this.schemaName = checkNotEmpty(schemaName, "schemaName").toLowerCase(ENGLISH);
            this.tableName = checkNotEmpty(tableName, "tableName").toLowerCase(ENGLISH);
        }
    }
